language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    secure: CIbfo8UAQCR9hPmfzGzeugwgGMYVB1o5QlKTVxS6qSMCnBCjr/g1uElfaGO+8ceoeOcrxSY4YX755RqfWg9KXWlZK2LhVdS13M2Ow1P0Mg89QIPjPJG4umbH/0dU9rKV01Jbh5RJFgthXKDaL8nD5QpzvF0c1fjEZD6+bfhXXGU=
